Fastapi and dynamodb microservice
Evgeniy-kl/Innowise-Trainee-task-fastapi pull request #1
Opened 2022-06-13 14:15 UTC by Evgeniy-kl

2022-06-14 10:20 UTC, akulakousky-innowise requested changes

2022-06-14 10:20 UTC, akulakousky-innowise commented on README.md
> +DELETE : localhost:5001/delete/
мнк кажется это не надо потому что изначально в фастапи есть документация с помощью сваггера

2022-06-14 10:20 UTC, akulakousky-innowise commented on app/Dockerfile
> +CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5001", "--reload"]
хотелось бы все таки тут тоже видеть энтрипоинт

2022-06-14 10:20 UTC, akulakousky-innowise commented on app/consumer.py
> +parameters = pika.ConnectionParameters('moose.rmq.cloudamqp.com',
хотелось бы это все видеть обернутое в класс для более генерного подхода

2022-06-14 10:20 UTC, akulakousky-innowise commented on app/database/db.py
> +        for table in tables:
а если ошибка будет на одной бд то что делать?

2022-06-14 10:20 UTC, akulakousky-innowise commented on app/funcs.py
> +def create_user(user: dict):
в тайпинге дикте обычно ключ значение объявляется

2022-06-14 10:20 UTC, akulakousky-innowise commented on app/funcs.py
> +        return JSONResponse(content=e.response["Error"], status_code=500)
а вообще хотелось бы это все видеть обернутое в класс и функции эти не должны возвращать респонс, потому что респонс выдают вьюхи

2022-06-14 10:20 UTC, akulakousky-innowise commented on app/main.py
> +create_tables()
у фастапи есть хук on_startup

2022-06-14 10:20 UTC, akulakousky-innowise commented on app/models.py
> +class UserStat(BaseModel):
по факту это схема а не модель, хоть в пудунтике это называется модель

2022-06-14 10:20 UTC, akulakousky-innowise commented on app/producer.py
> +credentials = pika.PlainCredentials('nzocntbp', 'bLDWuRiZsMh96jL2d0yCAiMvvWtBvpTr')
то эе самое что и в консьюмере

2022-06-14 10:20 UTC, akulakousky-innowise commented on app/routers/routers.py
> +@router.get('/get/{email}')
тут лучше еще указать response_model
ну и в общем и так понятно что это гет изза метода

2022-06-14 10:20 UTC, akulakousky-innowise commented on app/routers/routers.py
> +@router.post("/delete")
почему у тебя делит на посте?

2022-06-14 10:20 UTC, akulakousky-innowise commented on app/services.py
> +        print(f'SET #{field} = {field} + :val')
логирование ставь через logging

2022-06-14 12:01 UTC, Evgeniy-kl commented on app/database/db.py
> +        for table in tables:
не знаю..

2022-06-14 12:02 UTC, Evgeniy-kl commented on app/funcs.py
> +def create_user(user: dict):
не пойму, как это
**kwargs?

2022-06-14 13:13 UTC, akulakousky-innowise commented on app/funcs.py
> +def create_user(user: dict):
`user: dict[str, str]`  к примеру

2022-06-14 14:58 UTC, Evgeniy-kl commented on app/funcs.py
> +def create_user(user: dict):
окей, но мне в итоге вообще create не нужен, это окончательный результат

2022-06-15 10:13 UTC, akulakousky-innowise requested changes

2022-06-15 10:13 UTC, akulakousky-innowise commented on app/consumer.py
> +
я имел в виду весь консьюмер вынести)

2022-07-20 10:54 UTC, merged